### ISSUE TITLE
IOException: Stream closed

### ISSUE THREAD

**Issue by yogurtearl** [tbroyer/gradle-errorprone-plugin-v0.0.x#56] opened 2017-11-16 00:13 UTC
Our builds fail with this exception occasionally, but most of the time it works fine. 

plugin version 0.0.11

```
Caused by: org.gradle.internal.UncheckedException: java.lang.reflect.InvocationTargetException
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:75)
	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:24)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:207)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:192)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:124)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:95)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 31 more
Caused by: java.lang.reflect.InvocationTargetException
	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:63)
	... 52 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
	at com.google.errorprone.BaseErrorProneJavaCompiler.setupMessageBundle(BaseErrorProneJavaCompiler.java:195)
	at com.google.errorprone.BaseErrorProneJavaCompiler.getTask(BaseErrorProneJavaCompiler.java:81)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:127)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:108)
	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:119)
	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:66)
	... 53 more
Caused by: java.io.IOException: Stream closed
	... 59 more
```

**Comment by tbroyer** [comment] 2017-11-16 10:33
I have absolutely no idea where that could come from.

It looks like you're not using the latest Error Prone version, and that line in `BaseErrorProneJavaCompiler` would point to a `ResourceBundle.getBundle` call. The class loader used by the gradle-errorprone-plugin has really nothing special that could cause a "stream closed" exception; so I doubt this error comes from bugs in either the gradle-errorprone-plugin or Error Prone itself.

@cushon, any idea?

Closing anyway, as I don't see how this is actionable on gradle-errorprone-plugin side.

**Closed as completed by tbroyer** 2017-11-16 10:33 UTC
Labels: question

**Comment by tom-smalls** [comment] 2018-02-12 10:23
Was any progress made on this? We are using the latest version of error prone and the gradle plugin

**Comment by AndreyNudko** [comment] 2018-02-13 16:16
We believe this is to do with sharing JarFile instance between multiple URLClassloader-s in different threads. This means for all Jars loaded via a JarURLConnection, when one of the threads closes the JarFile it will close the instance for all other threads.

We have an experimental workaround to solving this that does the following (unfortunately you can only change the default caching flag through an instance method), which is called in our parent gradle file.

```java
new HttpURLConnection(null) {

        @Override
        public void connect() throws IOException {
        }

        @Override
        public void disconnect() {
        }

        @Override
        public boolean usingProxy() {
            return false;
        }
    }.setDefaultUseCaches(false);
```

See https://bugs.openjdk.java.net/browse/JDK-8163449 for a "fix" from Java 9 onwards

**Comment by AndreyNudko** [comment] 2018-02-13 18:01
To expand on the previous comment - this is my understanding of what's going on:
 - java.util.ResourceBundle.Control opens stream by calling `classLoader.getResourceAsStream(resourceName)`
 - classLoader is SelfFirstClassLoader from the plugin which extends URLClassLoader, but does not override getResourceAsStream()
 - URLClassLoader however has some special logic for jar resources - it remembers JarFile instance, so closing ClassLoader will close JarFile
 - the issue is how JarURLConnection gets JarFile: `JarFileFactory.get(this.getJarFileURL(), this.getUseCaches())`; getUseCaches() is initialized to static default value which is true, so by default all threads will use same instance of JarFile

As a result the following race is possible during parallel build (not having enough resources in CI probably makes it more likely)
Thread-1 opens stream using JarFile instance
Thread-2 opens second stream using same JarFile instance
Thread-2 finishes compilation and closes classloader - and so underlying JarFile and all its InputStream-s
Thread-1 tries to read from closed file and gets  _ZipFile closed_ or _IOException_ - depending on whether it's managed to enter actual read()
