### ISSUE TITLE
Only old versions

### ISSUE THREAD

**Issue by sneakythr0ws** [tbroyer/gradle-errorprone-plugin-v0.0.x#48] opened 2017-08-04 13:44 UTC
![image](https://user-images.githubusercontent.com/1594945/28971259-fdcec370-7933-11e7-9f93-3ab837ed8d48.png)

https://jcenter.bintray.com/net/ltgt/gradle/gradle-errorprone-plugin/

![image](https://user-images.githubusercontent.com/1594945/28971390-6da4e832-7934-11e7-84b5-31a68d4cfd81.png)

https://search.maven.org/#search%7Cga%7C1%7Cgradle-errorprone-plugin

**Comment by JakeWharton** [comment] 2017-08-04 14:08
New versions are in the Gradle plugin portal.

**Comment by tbroyer** [comment] 2017-08-04 14:10
Duplicate of #11

**Closed as completed by tbroyer** 2017-08-04 14:10 UTC
Labels: duplicate
